### ISSUE TITLE
Child/parent commands + individual commands

### ISSUE THREAD

**Issue by jonahseguin** [xxyy/intake-spigot#4]
Is there support for adding nested commands that aren't all in the same class?

Let's say i have the parent command "permissions"
And for each 'subcommand', i want it to have it's own class: ex _CmdAddGroup_
Where the aliases in the `@Command` for the subgroup are just `{ "addgroup" }`

So I should be able to execute /permissions addgroup

This works fine with only one registered using `commandManager.register(new CmdAddGroup(), "permissions");`

However, as soon as I add ANOTHER 'subcommand' with the same 'parent':
ex. `commandManager.register(new Cmd_Remove_Group(), "permissions");`
(where the `@Command` aliases for CmdRemoveGroup would be `{ "removegroup" }`
...
I get this error:
`java.lang.IllegalArgumentException: Can't add the command 'permissions' because SimpleDispatcher does not support replacing commands
        at com.sk89q.intake.dispatcher.SimpleDispatcher.registerCommand(SimpleDispatcher.java:78) ~[?:?]
        at com.sk89q.intake.fluent.DispatcherNode.group(DispatcherNode.java:87) ~[?:?]
        at li.l1t.common.intake.CommandBuilder.withDispatcherFor(CommandBuilder.java:64) ~[?:?]
        at li.l1t.common.intake.CommandsManager.registerCommand(CommandsManager.java:146) ~[?:?]`

Also, is there no way to register SINGLE commands (ex not with a parent?)

If i just wanted to have a command 'test', how could I register that? @xxyy

**Comment by literalplus** [comment]
Thanks for reporting this!

For the 'test' command:
You can register a handler for the root command using an empty string as alias, like this:
https://github.com/xxyy/expvp/blob/a850f1ae9db3391c7142b0d20e5c854f3c6f0732/src/main/java/me/minotopia/expvp/command/CommandSkills.java#L42

For the subcommands without subclasses, Intake does seem to allow this (not sure!). I've added a method so that you can test this. (The project architecture isn't quite ready for automated tests yet, sorry!)

Take this code: https://github.com/xxyy/intake-spigot/blob/master/src/main/java/li/l1t/common/intake/CommandsManager.java#L157, and add a [`withSubHandler(handler, aliases...)`](https://github.com/xxyy/intake-spigot/blob/f4022b85c6881adee886318e49148fbcd8431602/src/main/java/li/l1t/common/intake/CommandBuilder.java#L79) line directly after the call to `withDispatcherFor`. The first argument is a handler object (e,g. `new Cmd_Remove_Group()`), and the varargs argument are the aliases, like in the annotation (e.g. `"remove", "rem"`).

I can't guarantee that this works, I don't have time or a set-up project to test this atm. If it fails with an Intake exception, please attach it to this issue and maybe we can find a workaround. If it doesn't I'll add a proper API for this.

**Comment by literalplus** [comment]
Any news on this? Are you still interested in this? @jonahseguin

**Comment by jonahseguin** [comment]
I was having trouble debugging this because there was/is no build for the patch you added, as far as I'm aware?  Or is there a version that includes the withSubHandler(handler, aliases...)?
I'm effectively trying to create a command sequence similar to the bottom of your examples on the README (the image with the commands in gold)
ex /parent sub args
/parent sub2 args
/parent sub3 args

**Comment by literalplus** [comment]
Oh, yeah, forgot to link the build. The latest should include it: https://ci.l1t.li/job/public~intake-spigot/213/

**Comment by literalplus** [comment]
I verified that this actually works and have a working example you can take a look at:
https://github.com/xxyy/intake-spigot-test/tree/master/src/main/java/li/l1t/test/intake

The release with the new API is available here:
https://ci.l1t.li/job/public~intake-spigot/lastRelease/
